package com.ledgerbridge.audit.model;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    PERMISSION_DENIED,
    ALERT_REVIEWED,
    TRANSACTION_INITIATED,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    TRANSFER_INITIATED,
    ACCOUNT_CREATED,
    ACCOUNT_FROZEN,
    ACCOUNT_CLOSED
}
